### ISSUE TITLE
It does work in neovim on windows

### ISSUE THREAD

**Issue by ZG-N1** [zhenyangze/vim-bitoai#1]
when i use the command BitoAiExplain, Neovim put out  " only -p flag is applicable for this command. Remove any additional flags and then try again＂
firstly, I thought it was the cmdList variable in your bitoai.vim goes wrong but i echo it out and find it is correct.
I try to fix it but failed.
so can you do some research to fix this problem, that were be so helpfull

finally, so sorry about my poor English.

**Comment by zhenyangze** [comment]
Please tell me about your version of neovim

**Comment by zjp-CN** [comment]
I meet the same problem with latest nigtly neovim on Windows.

 Bito cli works fine on command line, 

```
bito -p C:\Users\ADMINI~1\AppData\Local\Temp\nvim.0\BJnNcn\3 -f C:\Users\ADMINI~1\AppData\Local\Temp\nvim.0\BJnNcn\2
```

but vim-bitoai opens a new window showing

```
Only "-p" flag is applicable for this command. Remove any additional flags and then try again.
```
